stages:
  - build
  - publish
  - release

variables:
  PACKAGE_DIR: "${CI_PROJECT_DIR}/_build/default/lib"

build-job:
  stage: build
  image: erlang:23.0.3-alpine
  before_script:
    -  apk add --no-cache snappy-dev openssl-dev alpine-sdk bsd-compat-headers bash
  script:
    - echo "Compiling the code..."
    - make rel
  artifacts:
    paths:
      - "${PACKAGE_DIR}"
    expire_in: 2 week
  # only:
  #   - main
  #   - tags
  #   # - /.*feature.*/

upload-to-arifactory:
  stage: publish
  script:
    - echo "Uploading enahnced-auth plugin..."
    - ls -la "${PACKAGE_DIR}"/vmq_enhanced_auth/
    # - |
      # curl -u $ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD \
      #  -XPUT "https://artifactory-gojek.golabs.io/artifactory/vernemq-plugins/enahnced-auth/enahnced-auth-$CI_COMMIT_TAG/" \
      #  --upload-file "${PACKAGE_DIR}"/vmq_enhanced_auth/*
    - echo "Uploading events-sidecar plugin..."
    - ls -la "${PACKAGE_DIR}"/vmq_events_sidecar/
    # - |
    #   curl -u $ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD \
    #    -XPUT "https://artifactory-gojek.golabs.io/artifactory/vernemq-plugins/events-sidecar/events-sidecar-$CI_COMMIT_TAG/" \
    #    --upload-file "${PACKAGE_DIR}"/vmq_events_sidecar/*
    - echo "Uploading metrics-plus plugin..."
    - ls -la 
    # - |
    #   curl -u $ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD \
    #    -XPUT "https://artifactory-gojek.golabs.io/artifactory/vernemq-plugins/metrics-plus/metrics-plus-$CI_COMMIT_TAG/" \
    #    --upload-file "${PACKAGE_DIR}"/vmq_metrics_plus/*
  only:
    - tags
  when: manual
  dependencies: 
    - build-job

# release-customer-broker:
#   stage: release
#   script:
#     - echo "releasing plugins..."
#   only:
#     - tags
#   when: manual
