name: Build and Publish plugins

on:
  push:
    branches:
      - 'main'
  pull_request:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  code_checks:
    name: Build plugins
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 23.0
          version-type: strict
      - run: sudo apt-get -y install libsnappy-dev
      - name: Compile
        run: make rel
      - name: Build directory
        run: ls -la _build/default/lib
